[[language]]
name = "go"
auto-format = true
language-servers = ["gopls", "golangci-lint-lsp", "gpt"]

[language-server.gopls]
command = "gopls"

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]

[language-server.gpt]
command = "helix-gpt"
args = ["--handler", "copilot"]
